<body>
    <h1>Styleguide</h1>
    <div class="block-color">
        <div class="style-color">Colours</div>
        <hr>
        <div class="color-detail">
            <div class="col1">BRAND COLOURS
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for buttons, some icons and text.</p>
                </div>
                <div>Primary</div>
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for top bar, some icons and text.</p>
                </div>
                <div>Secondary</div>
            </div>
            <div class="col2">TYPOGRAPHY COLOURS
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for H1, H2, H3, H4 and H5 text.</p>
                </div>
                <div>Headings</div>
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for paragraph text.</p>
                </div>
                <div>Body</div>
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for paragraph text that is a hyperlink.</p>
                </div>
                <div>Link Text</div>
            </div>
            <div class="col3">BACKGROUND COLOURS
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for the background colour on some content blocks.</p>
                </div>
                <div>Background 1</div>

                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for the background colour on the footer</p>
                </div>
                <div>Background 2</div>
            </div>
            <div class="col4">ADDITIONAL COLOURS
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for dividing lines and held outlines/ borders.</p>
                </div>
                <div>Line Fill</div>
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for error messages and sale badge/ price.</p>
                </div>
                <div>Error/Sale</div>
                <div class="col-inner">
                    <div class="square"></div>
                    <p>Used for page backgrond colour.</p>
                </div>
                <div>White</div>
            </div>
        </div>
    </div>

    <div class="block-typo">
        <div class="style-typo">
            Typography
        </div>
        <hr>
        <div class="typo-detail">
            <div class="col1">HEADING
                <h1>Heading 1</h1>
                <h2>Heading 2</h2>
                <h3>Heading 3</h3>
                <h4>HEADING 4</h4>
                <h5>HEADING 5</h5>
            </div>
            <div class="col2">PARAGRAPH
                <div class="row1">
                    <p>This is a paragraph style omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                        totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                    </p>
                </div>
                <div class="row2">
                    <div class="col1">TEXT LINKS
                        <div class="text-link">
                            <div class="col-inner">Text Link</div>
                            <div class="col-inner">Text Link Hover</div>
                        </div>
                    </div>
                    <div class="col2">ERROR
                        <div class="col-inner">Error text</div>
                    </div>
                    <div class="col3">PARAGRAPH BOLD
                        <div class="col-inner">Bold text</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="block-buttons">
        <div class="style-btn">Buttons</div>
        <hr>
        <div class="buttons-detail">
            <div class="row1">
                <div class="row-inner">&nbsp</div>
                <div class="row-inner">Primary</div>
                <div class="row-inner">Hollow</div>
                <div class="row-inner">Secondary</div>
            </div>
            <div class="row2">
                <div class="btn-type">Standard</div>
                <button class="action primary"><span>Button</span></button>
                <button class="action hollow"><span>Button</span></button>
                <button class="action secondary"><span>Button &nbsp</span><i class="fa-solid fa-arrow-right-long"></i></button>
            </div>
            <div class="row3">
                <div class="btn-type">Hover</div>
                <button class="action primary"><span>Button</span></button>
                <button class="action hollow"><span>Button</span></button>
                <button class="action secondary"><span>Button &nbsp</span><i class="fa-solid fa-arrow-right-long"></i></button>
            </div>
            <div class="row4">
                <div class="btn-type">Inactive</div>
                <button class="inactive"><span>Button</span></button>
            </div>

        </div>
    </div>
    <div class="block-noti">
        <div class="style-noti">Notification Banners</div>
        <hr>
        <div class="messages">
            <div class="message success">success/ standard notification</div>
            <br>
            <div class="message error">error notification</div>
        </div>
    </div>
    <div class="block-input">
        <div class="style-inputs">Inputs</div>
        <hr>
        <div class="inputs-detail">
            <div class="field">
                <input class="input-text" placeholder="Text Field" type="text" />
                <input class="input-text" placeholder="Active Field" type="text" />
                <input class="input-text" placeholder="Entered Field" type="text" />
                <input class="input-text" placeholder="Error Field" type="text" />
            </div>
        </div>
    </div>
</body>